openapi: 3.0.0
info:
  title: Credit Rating Report API
  description: API for generating and managing credit rating reports, as well as user authentication for login and logout.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
    description: Local development server
  - url: http://13.238.253.223:8000
    description: AWS EC2 instance

paths:
  /api/get-report:
    get:
      summary: Get a list of credit rating reports
      description: |
        This endpoint returns a list of credit rating reports based on optional filters like company name, company ID, report creation date, and whether to limit the reports to the authenticated user's own reports. Only one of `company_name` or `company_id` can be provided. Users must authenticate using basic authentication.
      tags:
        - Reports
      operationId: getCreditRatingReports
      parameters:
        - name: company_name
          in: query
          required: false
          description: Filter reports by the company's name (case-insensitive).
          schema:
            type: string
        - name: company_id
          in: query
          required: false
          description: Filter reports by the company's ID.
          schema:
            type: integer
        - name: start_date
          in: query
          required: false
          description: Filter reports created after or on this date (YYYY-MM-DD).
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: false
          description: Filter reports created before or on this date (YYYY-MM-DD).
          schema:
            type: string
            format: date
        - name: user_only
          in: query
          required: false
          description: Only show reports generated by the authenticated user. Set to 'true' to enable.
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: A list of matching credit rating reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreditRatingReport'
              examples:
                default:
                  summary: Example report
                  value: [
                    {
                      "id": 1,
                      "company": {
                        "id": 27053,
                        "name": "American Airlines Group Inc",
                        "country_name": "United States",
                        "security_number": 59261,
                        "ticker": "AAL US",
                        "id_bb_unique": "EQ0000000033024206",
                        "id_bb_company": "100090",
                        "security_type": "Common Stock",
                        "market_status": "ACTV",
                        "exchange_country_id": 15,
                        "domicile_id": 15,
                        "industry_sector_num": 10004,
                        "industry_group_num": 20018,
                        "industry_subgroup_num": 20,
                        "revision": 52486,
                        "start_date": "2016-12-29",
                        "end_date": null,
                        "flag": 1
                      },
                      "report_content": "Based on the general company data provided and my knowledge, I will create a short credit rating report for American Airlines Group Inc.\n\n**Company Overview**\n\nAmerican Airlines Group Inc. (AAL US) is a major airline operator in the United States, formed by the merger of AMR Corporation and US Airways Group in 2013. The company operates a fleet of aircraft, providing passenger and cargo transportation services worldwide.\n\n**Industry Analysis**\n\nThe airline industry is highly competitive, capital-intensive, and vulnerable to economic downturns, fuel price volatility, and geopolitical risks. However, American Airlines Group Inc. is one of the largest players in the industry, with a significant market share and a diversified route network.\n\n**Financial Analysis**\n\nUnfortunately, no financial ratios or recent financial statements (e.g., 10-K reports) are available for this assessment. However, I can use publicly available industry data to provide a general analysis.\n\nAs of 2022, American Airlines Group Inc. reported:\n\n- Revenue: $49.06 billion\n- Net Loss: ($-3.86 billion)\n- Total Debt: $47.8 billion\n- Total Equity: $14.35 billion\n- Total Employees: 128,900\n\nKeep in mind that these numbers may not reflect the current financial situation of the company.\n\n**Credit Rating Assessment**\n\nBased on the industry analysis, company size, and available financial data, I would assess the credit rating for American Airlines Group Inc. as follows:\n\n- **Credit Rating:** BB- (Speculative grade)\n- **Outlook:** Stable\n\nRationale:\n\n* Industry risks: The airline industry is vulnerable to various risks, such as fuel price volatility, economic downturns, and geopolitical tensions.\n* Company size and market share: American Airlines Group Inc. is one of the largest players in the industry, which provides some stability and resilience to economic shocks.\n* Financial performance: While the company reported significant losses in 2022, it has a substantial debt burden, which is a concern for credit rating.\n* Liquidity: The company has access to significant liquidity sources, including a large cash balance and committed credit facilities, which supports its credit profile.\n\n**Rating Limitations**\n\nThis credit rating assessment is based on limited information and should not be considered as investment advice.\n\n**Created At**: 2024-10-06T09:30:29.208771Z",
                      "user": {
                        "id": 1,
                        "username": "bob"
                      }
                    }
                  ]
        '400':
          description: Invalid query parameters, or both company_name and company_id were provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: No reports found matching the given criteria.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
      security:
        - BasicAuth: []

  /api/generate/:
    post:
      summary: Generate a new credit rating report
      description: |
        This endpoint generates a credit rating report based on the company's name or ID. Users can optionally use an LLM (language model) to enhance the report generation process. The request must provide either `company_name` or `company_id`, but not both. Users must authenticate using basic authentication.
      tags:
        - Reports
      operationId: createCreditRatingReport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                company_name:
                  type: string
                  description: The name of the company for which the report is being generated.
                  example: "Amazon"
                company_id:
                  type: integer
                  description: The ID of the company for which the report is being generated.
                  example: 123
                use_llm:
                  type: boolean
                  description: Whether to use an LLM (language model) to enhance the report.
                  example: true
      responses:
        '201':
          description: The report was successfully generated.
          content:
            application/json:
              schema:
                type: object
              examples:
                default:
                  summary: Example generated report
                  value: {
                    "report_id": 1,
                    "company_name": "American Airlines Group Inc",
                    "report_content": "Based on the general company data provided and my knowledge, I will create a short credit rating report for American Airlines Group Inc.\n\n**Company Overview**\n\nAmerican Airlines Group Inc. (AAL US) is a major airline operator in the United States, formed by the merger of AMR Corporation and US Airways Group in 2013. The company operates a fleet of aircraft, providing passenger and cargo transportation services worldwide.\n\n**Industry Analysis**\n\nThe airline industry is highly competitive, capital-intensive, and vulnerable to economic downturns, fuel price volatility, and geopolitical risks. However, American Airlines Group Inc. is one of the largest players in the industry, with a significant market share and a diversified route network.\n\n**Financial Analysis**\n\nUnfortunately, no financial ratios or recent financial statements (e.g., 10-K reports) are available for this assessment. However, I can use publicly available industry data to provide a general analysis.\n\nAs of 2022, American Airlines Group Inc. reported:\n\n- Revenue: $49.06 billion\n- Net Loss: ($-3.86 billion)\n- Total Debt: $47.8 billion\n- Total Equity: $14.35 billion\n- Total Employees: 128,900\n\nKeep in mind that these numbers may not reflect the current financial situation of the company.\n\n**Credit Rating Assessment**\n\nBased on the industry analysis, company size, and available financial data, I would assess the credit rating for American Airlines Group Inc. as follows:\n\n- **Credit Rating:** BB- (Speculative grade)\n- **Outlook:** Stable\n\nRationale:\n\n* Industry risks: The airline industry is vulnerable to various risks, such as fuel price volatility, economic downturns, and geopolitical tensions.\n* Company size and market share: American Airlines Group Inc. is one of the largest players in the industry, which provides some stability and resilience to economic shocks.\n* Financial performance: While the company reported significant losses in 2022, it has a substantial debt burden, which is a concern for credit rating.\n* Liquidity: The company has access to significant liquidity sources, including a large cash balance and committed credit facilities, which supports its credit profile.\n\n**Rating Limitations**\n\nThis credit rating assessment is based on limited information and should not be considered as investment advice.",
                    "created_at": "2024-10-06T09:30:29.208771Z"
                  }
        '400':
          description: Invalid input, such as providing both `company_name` and `company_id`, or incorrect data types.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: The company was not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: There was an error when using the LLM.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - BasicAuth: []
  
  api/register/:
    post:
      summary: Register a new user
      tags:
        - Users
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '201':
          description: User successfully registered
        '400':
          description: Bad request

  /api/login/:
    post:
      summary: Login a user
      tags:
        - Users
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: Successful login, returns token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
        '401':
          description: Unauthorized

  /api/logout/:
    post:
      summary: Logout the current user
      tags:
        - Users
      operationId: logoutUser
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logout successful"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Authentication credentials were not provided."
      security:
        - BasicAuth: []

components:
  schemas:
    CreditRatingReport:
      type: object
      properties:
        id:
          type: integer
        company:
          type: object
          $ref: '#/components/schemas/Company'
        report_content:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - company
        - report_content
        - created_at

    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        country_name:
          type: string
        security_number:
          type: integer
        ticker:
          type: string
      required:
        - id
        - name

    ReportGenerationRequest:
      type: object
      properties:
        company_name:
          type: string
        company_id:
          type: integer
        use_llm:
          type: boolean
      required:
        - company_name
        - company_id

    UserRegistrationRequest:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
          required:
            - username
            - password
    
    UserLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    AuthToken:
      type: object
      properties:
        token:
          type: string
      required:
        - token